import { useState } from 'react'
import { Activity, ArrowUpRight, Bell, Check, ChevronRight, CircleHelp, FolderKanban, LayoutDashboard, Plus, Search, Settings, Users, X } from 'lucide-react'
import { DEMOButton, DEMOCard, DEMOEmptyState, DEMOErrorState, DEMOStat, DEMOLoadingState, DEMOSectionHeader, DEMOThemeFrame, type DEMOPageState } from '@/common/DEMOComponents'

const projects = [{ name: 'Atlas redesign', type: '产品设计', progress: 82, members: 8, color: '#5e6ad2' }, { name: 'Mobile onboarding', type: '增长实验', progress: 54, members: 5, color: '#27a644' }, { name: 'Q3 research', type: '用户研究', progress: 31, members: 3, color: '#828fff' }]

export default function DEMOAdminSaasHome() {
  const [state, setState] = useState<DEMOPageState>('normal')
  const [active, setActive] = useState('概览')
  const [showNew, setShowNew] = useState(false)
  const [created, setCreated] = useState(false)
  return <DEMOThemeFrame theme="linear">
    <div className="mx-auto flex min-h-[calc(100vh-40px)] max-w-[1440px] flex-col md:flex-row">
      <aside className="hidden w-60 shrink-0 border-r p-5 md:block" style={{ borderColor: 'var(--demo-border)', background: 'var(--demo-surface)' }}><div className="flex items-center gap-2 text-sm font-semibold"><div className="flex h-7 w-7 items-center justify-center rounded-lg" style={{ background: 'var(--demo-accent)' }}><span className="h-2.5 w-2.5 rounded-full bg-white" /></div>DEMO / WORKSPACE</div><button type="button" className="mt-7 flex w-full items-center gap-2 rounded-lg border px-3 py-2 text-left text-sm" style={{ borderColor: 'var(--demo-border)', color: 'var(--demo-muted)' }}><Search size={15} />搜索 <span className="ml-auto text-[10px]">⌘ K</span></button><nav className="mt-6 space-y-1">{[{label: '概览', icon: LayoutDashboard}, {label: '项目', icon: FolderKanban}, {label: '成员', icon: Users}, {label: '活动', icon: Activity}].map(({ label, icon: Icon }) => <button type="button" key={label} onClick={() => setActive(label)} className="flex min-h-11 w-full items-center gap-3 rounded-lg px-3 text-sm font-medium" style={{ background: active === label ? 'var(--demo-surface-strong)' : 'transparent', color: active === label ? 'var(--demo-ink)' : 'var(--demo-muted)' }}><Icon size={16} />{label}</button>)}</nav><div className="mt-auto space-y-1 pt-8"><button type="button" className="flex min-h-11 w-full items-center gap-3 rounded-lg px-3 text-sm" style={{ color: 'var(--demo-muted)' }}><Settings size={16} />设置</button><button type="button" className="flex min-h-11 w-full items-center gap-3 rounded-lg px-3 text-sm" style={{ color: 'var(--demo-muted)' }}><CircleHelp size={16} />帮助中心</button></div></aside>
      <main className="min-w-0 flex-1"><header className="flex min-h-16 items-center justify-between gap-4 border-b px-4 sm:px-8" style={{ borderColor: 'var(--demo-border)', background: 'var(--demo-surface)' }}><div><p className="text-xs" style={{ color: 'var(--demo-muted)' }}>工作区 / {active}</p><p className="mt-1 text-sm font-semibold">Monday, September 14</p></div><div className="flex items-center gap-2"><button type="button" aria-label="查看通知" className="inline-flex min-h-11 min-w-11 items-center justify-center rounded-full" style={{ color: 'var(--demo-muted)' }}><Bell size={17} /></button><div className="flex h-9 w-9 items-center justify-center rounded-full text-xs font-bold" style={{ background: '#d9ddff', color: 'var(--demo-accent)' }}>ML</div></div></header>
        <div className="p-4 sm:p-8"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="text-sm font-medium" style={{ color: 'var(--demo-accent)' }}>早上好，Mia</p><h1 className="mt-2 font-[var(--demo-font-display)] text-3xl font-semibold tracking-[-0.05em] sm:text-5xl">今天要推进什么？</h1><p className="mt-3 text-sm" style={{ color: 'var(--demo-muted)' }}>你有 4 个待处理事项，团队正在按计划前进。</p></div><DEMOButton onClick={() => setShowNew(true)}><Plus size={17} />新建项目</DEMOButton></div>
          {state === 'loading' && <div className="mt-8"><DEMOLoadingState /></div>}{state === 'empty' && <div className="mt-8"><DEMOEmptyState title="还没有项目" description="创建第一个项目，让团队开始协作。" action={<DEMOButton onClick={() => setShowNew(true)}><Plus size={16} />创建项目</DEMOButton>} /></div>}{state === 'error' && <div className="mt-8"><DEMOErrorState onRetry={() => setState('normal')} /></div>}
          {state === 'normal' && <><div className="mt-8 grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><DEMOStat label="进行中的项目" value="12" change="+2 本周" icon={FolderKanban} /><DEMOStat label="团队成员" value="48" change="+6 本月" icon={Users} /><DEMOStat label="完成任务" value="326" change="+18.4%" icon={Check} /><DEMOStat label="活跃度" value="87%" change="+4.2%" icon={Activity} /></div><section className="mt-9"><DEMOSectionHeader eyebrow="YOUR PROJECTS" title="项目进度" action={<button type="button" className="inline-flex items-center gap-1 text-sm font-semibold" style={{ color: 'var(--demo-accent)' }}>查看全部 <ArrowUpRight size={15} /></button>} /><div className="grid gap-4 lg:grid-cols-3">{projects.map((project) => <DEMOCard key={project.name} className="p-5"><div className="flex items-start justify-between"><div className="flex h-10 w-10 items-center justify-center rounded-xl text-white" style={{ background: project.color }}><FolderKanban size={18} /></div><button type="button" aria-label={`${project.name} 更多操作`} className="inline-flex min-h-11 min-w-11 items-center justify-center rounded-full" style={{ color: 'var(--demo-muted)' }}>•••</button></div><h3 className="mt-5 font-semibold">{project.name}</h3><p className="mt-1 text-xs" style={{ color: 'var(--demo-muted)' }}>{project.type} · {project.members} 位成员</p><div className="mt-6 flex items-center justify-between text-xs"><span style={{ color: 'var(--demo-muted)' }}>完成度</span><span className="font-semibold">{project.progress}%</span></div><div className="mt-2 h-1.5 overflow-hidden rounded-full" style={{ background: 'var(--demo-surface-strong)' }}><div className="h-full rounded-full" style={{ width: `${project.progress}%`, background: project.color }} /></div></DEMOCard>)}</div></section><section className="mt-9 grid gap-4 lg:grid-cols-[1.2fr_0.8fr]"><DEMOCard className="p-5"><DEMOSectionHeader eyebrow="RECENT ACTIVITY" title="团队动态" action={<button type="button" className="text-sm font-semibold" style={{ color: 'var(--demo-accent)' }}>全部</button>} /><div className="space-y-4">{['Lena 完成了 Atlas redesign 的首页评审', 'Jon 加入了 Mobile onboarding 项目', '你将 Q3 research 标记为重点项目'].map((item, index) => <div key={item} className="flex items-start gap-3"><div className="mt-1 h-2 w-2 rounded-full" style={{ background: index === 0 ? 'var(--demo-accent)' : 'var(--demo-alt)' }} /><p className="text-sm leading-6">{item}<span className="ml-2 text-xs" style={{ color: 'var(--demo-muted)' }}>{index + 1}h</span></p></div>)}</div></DEMOCard><DEMOCard className="p-5"><DEMOSectionHeader eyebrow="NEXT UP" title="待处理事项" /><div className="space-y-2">{['Review onboarding copy', 'Share Q3 research', 'Invite design partner'].map((item) => <button type="button" key={item} className="flex min-h-11 w-full items-center justify-between rounded-xl px-3 text-left text-sm" style={{ background: 'var(--demo-surface-strong)' }}>{item}<ChevronRight size={15} style={{ color: 'var(--demo-muted)' }} /></button>)}</div></DEMOCard></section></>}
        </div></main>
    </div>
    {showNew && <div className="fixed inset-0 z-50 flex items-end justify-center bg-black/50 p-4 sm:items-center" onClick={(event) => { if (event.target === event.currentTarget) setShowNew(false) }}><div className="w-full max-w-lg rounded-2xl border p-6" style={{ borderColor: 'var(--demo-border)', background: 'var(--demo-surface)' }}><div className="flex items-center justify-between"><h2 className="text-xl font-semibold">新建项目</h2><button type="button" aria-label="关闭弹窗" onClick={() => setShowNew(false)} className="inline-flex min-h-11 min-w-11 items-center justify-center rounded-full" style={{ color: 'var(--demo-muted)' }}><X size={18} /></button></div><label htmlFor="demo-project-name" className="mt-6 block text-sm font-semibold">项目名称</label><input id="demo-project-name" className="mt-2 h-12 w-full rounded-xl border bg-transparent px-3 outline-none" style={{ borderColor: 'var(--demo-border)' }} placeholder="例如：Website refresh" /><DEMOButton className="mt-5 w-full" onClick={() => { setCreated(true); setShowNew(false) }}>创建项目</DEMOButton>{created && <p className="mt-3 flex items-center justify-center gap-1 text-xs font-semibold" style={{ color: 'var(--demo-alt)' }}><Check size={14} />项目创建成功</p>}</div></div>}
  </DEMOThemeFrame>
}
