import { useState } from 'react'
import { ArrowDownLeft, ArrowUpRight, Check, Copy, Eye, EyeOff, MoreHorizontal, Plus, RefreshCcw, ShieldCheck, WalletCards, X } from 'lucide-react'
import { DEMOBadge, DEMOButton, DEMOCard, DEMOEmptyState, DEMOErrorState, DEMOIconButton, DEMOLoadingState, DEMOSectionHeader, DEMOThemeFrame, type DEMOPageState } from '@/common/DEMOComponents'

const assets = [{ symbol: 'ETH', name: 'Ethereum', amount: '1.284', value: '$4,042.18', change: '+3.2%', color: '#627eea' }, { symbol: 'USDC', name: 'USD Coin', amount: '1,820.00', value: '$1,820.00', change: '+0.01%', color: '#2775ca' }, { symbol: 'BTC', name: 'Bitcoin', amount: '0.018', value: '$1,146.62', change: '-0.8%', color: '#f7931a' }]

export default function DEMOBlockchainWallet() {
  const [state, setState] = useState<DEMOPageState>('normal')
  const [visible, setVisible] = useState(true)
  const [copied, setCopied] = useState(false)
  const [panel, setPanel] = useState<'send' | 'receive' | null>(null)
  const [selected, setSelected] = useState(assets[0])

  const copyAddress = () => { setCopied(true); window.setTimeout(() => setCopied(false), 1600) }
  return <DEMOThemeFrame theme="coinbase">
    <div className="mx-auto max-w-[1080px] px-4 py-5">
      <header className="flex items-center justify-between gap-4"><div className="flex items-center gap-3"><div className="flex h-10 w-10 items-center justify-center rounded-2xl" style={{ background: 'var(--demo-accent)', color: '#fff' }}><WalletCards size={19} /></div><div><p className="font-semibold">DEMO Wallet</p><p className="text-xs" style={{ color: 'var(--demo-muted)' }}>个人资产 · Mainnet</p></div></div><div className="flex items-center gap-2"><DEMOIconButton icon={RefreshCcw} label="刷新资产" /><DEMOIconButton icon={MoreHorizontal} label="更多设置" /></div></header>
      {state === 'loading' && <div className="mt-7"><DEMOLoadingState /></div>}
      {state === 'empty' && <div className="mt-7"><DEMOEmptyState title="还没有资产" description="连接一个安全钱包或购买你的第一笔数字资产。" action={<DEMOButton onClick={() => setState('normal')}><Plus size={16} />添加资产</DEMOButton>} /></div>}
      {state === 'error' && <div className="mt-7"><DEMOErrorState onRetry={() => setState('normal')} /></div>}
      {state === 'normal' && <>
        <section className="mt-7 rounded-[28px] p-6" style={{ background: 'linear-gradient(135deg, #0052ff, #003ecc)', color: '#fff' }}><div className="flex items-start justify-between gap-4"><div><p className="text-sm text-white/70">钱包总资产 · USD</p><div className="mt-3 flex items-center gap-3"><h1 className="text-4xl font-semibold tracking-[-0.06em]">{visible ? '$7,008.80' : '••••••'}</h1><button type="button" aria-label={visible ? '隐藏余额' : '显示余额'} onClick={() => setVisible(!visible)} className="inline-flex min-h-11 min-w-11 items-center justify-center rounded-full bg-white/15">{visible ? <Eye size={18} /> : <EyeOff size={18} />}</button></div><p className="mt-2 text-sm text-white/75">今日 <span className="font-semibold text-white">+$184.21（+2.7%）</span></p></div><DEMOBadge tone="neutral">已验证</DEMOBadge></div><div className="mt-8 flex flex-wrap gap-3"><DEMOButton tone="secondary" onClick={() => setPanel('send')}><ArrowUpRight size={16} />发送</DEMOButton><DEMOButton className="border-white/30 bg-white/10 text-white hover:bg-white/20" onClick={() => setPanel('receive')}><ArrowDownLeft size={16} />接收</DEMOButton></div></section>
        <div className="mt-8 grid gap-8"><section><DEMOSectionHeader eyebrow="YOUR ASSETS" title="资产组合" action={<button type="button" className="text-sm font-semibold" style={{ color: 'var(--demo-accent)' }}>查看全部</button>} /><div className="space-y-3">{assets.map((asset) => <button type="button" key={asset.symbol} onClick={() => setSelected(asset)} className="flex w-full items-center justify-between gap-4 rounded-[var(--demo-radius)] border p-4 text-left transition-shadow hover:shadow-md" style={{ borderColor: selected.symbol === asset.symbol ? 'var(--demo-accent)' : 'var(--demo-border)', background: 'var(--demo-surface)' }}><div className="flex items-center gap-3"><div className="flex h-10 w-10 items-center justify-center rounded-full text-sm font-bold text-white" style={{ background: asset.color }}>{asset.symbol.slice(0, 1)}</div><div><p className="font-semibold">{asset.name}</p><p className="mt-1 text-xs" style={{ color: 'var(--demo-muted)' }}>{asset.amount} {asset.symbol}</p></div></div><div className="text-right"><p className="font-semibold">{asset.value}</p><p className="mt-1 text-xs font-semibold" style={{ color: asset.change.startsWith('-') ? 'var(--demo-danger)' : 'var(--demo-alt)' }}>{asset.change}</p></div></button>)}</div></section><section><DEMOSectionHeader eyebrow="SECURITY" title="钱包安全" /><DEMOCard className="p-5"><div className="flex items-start gap-3"><div className="rounded-xl p-2" style={{ background: '#e7f8ef', color: 'var(--demo-alt)' }}><ShieldCheck size={20} /></div><div><p className="font-semibold">保护等级：高</p><p className="mt-1 text-sm leading-6" style={{ color: 'var(--demo-muted)' }}>双重验证已开启，恢复短语仅保存在你的设备上。</p></div></div><div className="mt-5 rounded-2xl p-4" style={{ background: 'var(--demo-surface-strong)' }}><p className="text-xs" style={{ color: 'var(--demo-muted)' }}>钱包地址</p><div className="mt-2 flex items-center justify-between gap-3"><code className="truncate text-sm">0x71C7...A91F</code><button type="button" aria-label="复制钱包地址" onClick={copyAddress} className="inline-flex min-h-11 min-w-11 items-center justify-center rounded-full" style={{ color: 'var(--demo-accent)' }}>{copied ? <Check size={17} /> : <Copy size={17} />}</button></div>{copied && <p className="mt-2 text-xs font-semibold" style={{ color: 'var(--demo-alt)' }}>地址已复制</p>}</div></DEMOCard></section></div>
        <DEMOCard className="mt-8 p-5"><div className="flex items-center justify-between"><div><p className="text-sm font-semibold">{selected.name} 价格走势</p><p className="mt-1 text-xs" style={{ color: 'var(--demo-muted)' }}>过去 7 天 · USD</p></div><DEMOBadge tone={selected.change.startsWith('-') ? 'danger' : 'success'}>{selected.change}</DEMOBadge></div><div className="mt-5 flex h-28 items-end gap-2">{[35, 45, 42, 62, 51, 74, 68, 85, 78, 94, 88, 100].map((height, index) => <div key={index} className="flex-1 rounded-t-lg" style={{ height: `${height}%`, background: index === 11 ? 'var(--demo-accent)' : 'color-mix(in srgb, var(--demo-accent) 22%, var(--demo-surface-strong))' }} />)}</div></DEMOCard>
      </>}
      {panel && <div className="fixed inset-0 z-50 flex items-end justify-center bg-black/40 p-4" onClick={(event) => { if (event.target === event.currentTarget) setPanel(null) }}><div className="w-full max-w-md rounded-[28px] p-6" style={{ background: 'var(--demo-surface)' }}><div className="flex items-center justify-between"><h2 className="text-xl font-semibold">{panel === 'send' ? '发送资产' : '接收资产'}</h2><button type="button" aria-label="关闭弹窗" onClick={() => setPanel(null)} className="inline-flex min-h-11 min-w-11 items-center justify-center rounded-full" style={{ color: 'var(--demo-muted)' }}><X size={18} /></button></div><p className="mt-2 text-sm" style={{ color: 'var(--demo-muted)' }}>{panel === 'send' ? '选择资产并填写收款地址，交易提交前请再次核对网络和手续费。' : '将地址或二维码分享给对方，确认网络一致后再接收资产。'}</p>{panel === 'send' ? <><label className="mt-5 block text-sm font-semibold" htmlFor="demo-send-address">收款地址</label><input id="demo-send-address" className="mt-2 h-12 w-full rounded-xl border px-3 outline-none" style={{ borderColor: 'var(--demo-border)', background: 'var(--demo-bg)' }} placeholder="0x..." /><DEMOButton className="mt-5 w-full" onClick={() => setPanel(null)}>继续</DEMOButton></> : <><div className="mx-auto mt-6 flex h-36 w-36 items-center justify-center rounded-2xl border-4 border-dashed text-center text-xs font-semibold" style={{ borderColor: 'var(--demo-accent)', color: 'var(--demo-accent)' }}>DEMO<br />QR CODE</div><code className="mt-5 block rounded-xl p-3 text-center text-xs" style={{ background: 'var(--demo-surface-strong)' }}>0x71C7...A91F</code></>}</div></div>}
    </div>
  </DEMOThemeFrame>
}
