import { useState } from 'react'
import { Activity, CalendarDays, CheckCircle2, Clock3, Dumbbell, Flame, Footprints, Moon, Play, Sparkles } from 'lucide-react'
import { DEMOBadge, DEMOButton, DEMOCard, DEMOEmptyState, DEMOErrorState, DEMOLoadingState, DEMOProgress, DEMOSectionHeader, DEMOThemeFrame, type DEMOPageState } from '@/common/DEMOComponents'

const sessions = [
  { title: '晨间活力唤醒', type: '瑜伽 · 初级', duration: '12 min', color: '#ffce00', icon: Activity },
  { title: '午后核心训练', type: '力量 · 中级', duration: '24 min', color: '#0061ef', icon: Dumbbell },
  { title: '睡前舒缓拉伸', type: '拉伸 · 全等级', duration: '10 min', color: '#3b197f', icon: Moon },
]

export default function DEMOSportsHealthHome() {
  const [state, setState] = useState<DEMOPageState>('normal')
  const [tab, setTab] = useState<'today' | 'plans' | 'progress'>('today')
  const [started, setStarted] = useState<string | null>(null)
  const [completed, setCompleted] = useState(2)

  return <DEMOThemeFrame theme="headspace">
    <div className="mx-auto max-w-[1080px] px-4 py-5">
      <header className="flex items-center justify-between gap-4"><div className="flex items-center gap-3"><div className="flex h-10 w-10 items-center justify-center rounded-2xl" style={{ background: 'var(--demo-alt)', color: 'var(--demo-ink)' }}><Sparkles size={19} /></div><div><p className="text-sm font-bold">MORNING / MIND</p><p className="text-xs" style={{ color: 'var(--demo-muted)' }}>星期三，3 月 18 日</p></div></div><button type="button" aria-label="打开日历" className="inline-flex min-h-11 min-w-11 items-center justify-center rounded-full border" style={{ borderColor: 'var(--demo-border)', background: 'var(--demo-surface)' }}><CalendarDays size={18} /></button></header>
      {state === 'loading' && <div className="mt-7"><DEMOLoadingState /></div>}
      {state === 'empty' && <div className="mt-7"><DEMOEmptyState title="今天还没有计划" description="从一场 5 分钟的呼吸练习开始，建立你的第一个健康节奏。" action={<DEMOButton onClick={() => setState('normal')}>探索训练</DEMOButton>} /></div>}
      {state === 'error' && <div className="mt-7"><DEMOErrorState onRetry={() => setState('normal')} /></div>}
      {state === 'normal' && <>
        <section className="mt-7 grid gap-5"><div className="rounded-[32px] p-6" style={{ background: 'linear-gradient(135deg, #0061ef, #00a4ff)', color: '#ffffff' }}><DEMOBadge tone="neutral">今日推荐</DEMOBadge><h1 className="mt-7 max-w-lg text-4xl font-semibold leading-[1.05] tracking-[-0.05em]">给自己<br />留出 20 分钟。</h1><p className="mt-5 max-w-md text-sm leading-6 text-white/80">跟随教练完成一组低冲击训练，让身体醒来，也让注意力回到当下。</p><DEMOButton tone="secondary" className="mt-7" onClick={() => setStarted('晨间活力唤醒')}><Play size={16} fill="currentColor" />开始今日训练</DEMOButton></div><DEMOCard className="flex flex-col justify-between p-6"><div className="flex items-center justify-between"><div><p className="text-sm font-semibold">本周进度</p><p className="mt-1 text-xs" style={{ color: 'var(--demo-muted)' }}>连续第 4 周</p></div><Flame size={20} style={{ color: '#f97316' }} /></div><div className="my-5 flex items-center gap-5"><div className="relative flex h-28 w-28 items-center justify-center rounded-full" style={{ background: 'conic-gradient(var(--demo-accent) 72%, var(--demo-surface-strong) 0)' }}><div className="flex h-20 w-20 flex-col items-center justify-center rounded-full" style={{ background: 'var(--demo-surface)' }}><span className="text-2xl font-semibold">72%</span><span className="text-[10px]" style={{ color: 'var(--demo-muted)' }}>完成度</span></div></div><div className="space-y-3 text-xs" style={{ color: 'var(--demo-muted)' }}><p className="flex items-center gap-2"><Footprints size={15} style={{ color: 'var(--demo-accent)' }} />4 次训练</p><p className="flex items-center gap-2"><Clock3 size={15} style={{ color: 'var(--demo-accent)' }} />86 分钟</p></div></div><DEMOProgress value={72} label="距离周目标还差 2 次" /></DEMOCard></section>
        <div className="mt-9 flex gap-5 border-b" style={{ borderColor: 'var(--demo-border)' }}>{(['today', 'plans', 'progress'] as const).map((item) => <button key={item} type="button" onClick={() => setTab(item)} className="min-h-12 border-b-2 text-sm font-semibold" style={{ borderColor: tab === item ? 'var(--demo-accent)' : 'transparent', color: tab === item ? 'var(--demo-ink)' : 'var(--demo-muted)' }}>{item === 'today' ? '今日计划' : item === 'plans' ? '训练计划' : '我的进度'}</button>)}</div>
        {tab === 'today' && <section className="mt-7"><DEMOSectionHeader eyebrow="YOUR ROUTINE" title="接下来做什么？" description="为今天挑一场合适的练习，完成后会自动更新你的周进度。" /><div className="grid gap-4">{sessions.map((session) => <DEMOCard key={session.title} className="overflow-hidden"><div className="flex h-28 items-center justify-center" style={{ background: session.color }}><session.icon size={40} color={session.color === '#3b197f' ? '#ffffff' : '#2d2c2b'} /></div><div className="p-4"><div className="flex items-start justify-between gap-2"><div><h3 className="font-semibold">{session.title}</h3><p className="mt-1 text-xs" style={{ color: 'var(--demo-muted)' }}>{session.type} · {session.duration}</p></div><button type="button" aria-label={`开始${session.title}`} onClick={() => setStarted(session.title)} className="inline-flex min-h-11 min-w-11 items-center justify-center rounded-full" style={{ background: 'var(--demo-accent)', color: '#ffffff' }}><Play size={16} fill="currentColor" /></button></div>{started === session.title && <p className="mt-3 flex items-center gap-1 text-xs font-semibold" style={{ color: 'var(--demo-alt)' }}><CheckCircle2 size={14} />已加入今日计划</p>}</div></DEMOCard>)}</div></section>}
        {tab === 'plans' && <DEMOCard className="mt-7 p-6"><DEMOSectionHeader eyebrow="4 WEEK PLAN" title="从基础开始" description="每周 3 次，逐步建立力量、灵活性与恢复能力。" action={<DEMOButton onClick={() => setCompleted(completed + 1)}>加入计划</DEMOButton>} /><div className="space-y-3">{['第 1 周 · 觉察身体', '第 2 周 · 建立力量', '第 3 周 · 提升耐力'].map((item, index) => <div key={item} className="flex items-center justify-between rounded-2xl border p-4" style={{ borderColor: 'var(--demo-border)' }}><span className="text-sm font-semibold">{item}</span><DEMOBadge tone={index < completed ? 'success' : 'neutral'}>{index < completed ? '已完成' : '未开始'}</DEMOBadge></div>)}</div></DEMOCard>}
        {tab === 'progress' && <DEMOCard className="mt-7 p-6"><DEMOSectionHeader eyebrow="YOUR PROGRESS" title="稳定比极限更重要" /><div className="grid gap-4"><div><p className="text-xs" style={{ color: 'var(--demo-muted)' }}>训练天数</p><p className="mt-2 text-3xl font-semibold">18</p></div><div><p className="text-xs" style={{ color: 'var(--demo-muted)' }}>总时长</p><p className="mt-2 text-3xl font-semibold">6h 42m</p></div><div><p className="text-xs" style={{ color: 'var(--demo-muted)' }}>连续天数</p><p className="mt-2 text-3xl font-semibold">12</p></div></div><div className="mt-6"><DEMOProgress value={completed * 20 + 12} label="本月目标" color="var(--demo-alt)" /></div></DEMOCard>}
      </>}
    </div>
  </DEMOThemeFrame>
}
